insert into ingredients (id, name) values (1, 'Downy Lobelia');
insert into ingredients (id, name) values (2, 'Goldentop');
insert into ingredients (id, name) values (3, 'Mountain Fetterbush');
insert into ingredients (id, name) values (4, 'Wideleaf Racomitrium Moss');
insert into ingredients (id, name) values (5, 'Babington''s Graphina Lichen');
insert into ingredients (id, name) values (6, 'Livingrock');
insert into ingredients (id, name) values (7, 'Yellow Star-tulip');
insert into ingredients (id, name) values (8, 'Plummer''s Cliff Fern');
insert into ingredients (id, name) values (9, 'Sewer Vine');
insert into ingredients (id, name) values (10, 'Joinvillea');
insert into ingredients (id, name) values (11, 'Brazilian Nightshade');
insert into ingredients (id, name) values (12, 'Perplexed Halimolobos');
insert into ingredients (id, name) values (13, 'Bensoniella');
insert into ingredients (id, name) values (14, 'Parry''s False Prairie-clover');
insert into ingredients (id, name) values (15, 'Eared Willow');
insert into ingredients (id, name) values (16, 'Porsild''s Draba');
insert into ingredients (id, name) values (17, 'Clokey''s Milkvetch');
insert into ingredients (id, name) values (18, 'Chihuahuan Brickellbush');
insert into ingredients (id, name) values (19, 'Rim Lichen');
insert into ingredients (id, name) values (20, 'Ash Creek Mousetail');
insert into ingredients (id, name) values (21, 'Alkali Pepperweed');
insert into ingredients (id, name) values (22, 'Huachuca Mountain Spurge');
insert into ingredients (id, name) values (23, 'Maidenberry');
insert into ingredients (id, name) values (24, 'Bristlehead');
insert into ingredients (id, name) values (25, 'Browneyes');
insert into ingredients (id, name) values (26, 'Buttonweed');
insert into ingredients (id, name) values (27, 'Antioch Dunes Evening Primrose');
insert into ingredients (id, name) values (28, 'Wingleaf Soapberry');
insert into ingredients (id, name) values (29, 'Honeysuckle');
insert into ingredients (id, name) values (30, 'Steens Indian Paintbrush');
insert into ingredients (id, name) values (31, 'Rattlebox');
insert into ingredients (id, name) values (32, 'Dwarf Thistle');
insert into ingredients (id, name) values (33, 'Santa Barbara Ceanothus');
insert into ingredients (id, name) values (34, 'Hitchcock''s Mock Orange');
insert into ingredients (id, name) values (35, 'Eastwood''s Manzanita');
insert into ingredients (id, name) values (36, 'Washoe Pine');
insert into ingredients (id, name) values (37, 'Beardgrass');
insert into ingredients (id, name) values (38, 'Sticky Leaf Arnica');
insert into ingredients (id, name) values (39, 'Britton''s Shadow Witch');
insert into ingredients (id, name) values (40, 'Shelton''s Monardella');
insert into ingredients (id, name) values (41, 'Sierra Milkvetch');
insert into ingredients (id, name) values (42, 'Norwegian Timmia Moss');
insert into ingredients (id, name) values (43, 'Cyrtandra');
insert into ingredients (id, name) values (44, 'Bearded Cryptantha');
insert into ingredients (id, name) values (45, 'Hibberson''s Trillium');
insert into ingredients (id, name) values (46, 'Summer Snowflake');
insert into ingredients (id, name) values (47, 'Lake Quillwort');
insert into ingredients (id, name) values (48, 'Scurf Hoarypea');
insert into ingredients (id, name) values (49, 'Eastern Star Sedge');
insert into ingredients (id, name) values (50, 'Poorjoe');
insert into ingredients (id, name) values (51, 'Jeweled Thistle');
insert into ingredients (id, name) values (52, 'Asian Meadowsweet');
insert into ingredients (id, name) values (53, 'Canyon Schiedea');
insert into ingredients (id, name) values (54, 'Dotted Lichen');
insert into ingredients (id, name) values (55, 'Cow Itch Tree');
insert into ingredients (id, name) values (56, 'Senegal Boscia');
insert into ingredients (id, name) values (57, 'Ozark Grass');
insert into ingredients (id, name) values (58, 'Coyotethistle');
insert into ingredients (id, name) values (59, 'Gypsum Ringstem');
insert into ingredients (id, name) values (60, 'Cream Garland-lily');
insert into ingredients (id, name) values (61, 'Tennessee Bladderfern');
insert into ingredients (id, name) values (62, 'Common Chickweed');
insert into ingredients (id, name) values (63, 'Curtiss'' Loosestrife');
insert into ingredients (id, name) values (64, 'Desert Olive');
insert into ingredients (id, name) values (65, 'Scentless Bayberry');
insert into ingredients (id, name) values (66, 'Branched Lagophylla');
insert into ingredients (id, name) values (67, 'California Rockjasmine');
insert into ingredients (id, name) values (68, 'Beach Starwort');
insert into ingredients (id, name) values (69, 'Pacific Blacksnakeroot');
insert into ingredients (id, name) values (70, 'Scratchthroat');
insert into ingredients (id, name) values (71, 'Mearns'' Bird''s-foot Trefoil');
insert into ingredients (id, name) values (72, 'Heermann''s Buckwheat');
insert into ingredients (id, name) values (73, 'Darkstar Milkvine');
insert into ingredients (id, name) values (74, 'Rock Goldenrod');
insert into ingredients (id, name) values (75, 'Bigelow''s Willow');
insert into ingredients (id, name) values (76, 'Gulch Cyrtandra');
insert into ingredients (id, name) values (77, 'Pearthorn');
insert into ingredients (id, name) values (78, 'Bur-reed');
insert into ingredients (id, name) values (79, 'Mt. Lassen Clarkia');
insert into ingredients (id, name) values (80, 'Hyssopleaf Hedgenettle');
insert into ingredients (id, name) values (81, 'Littlesnout Sedge');
insert into ingredients (id, name) values (82, 'Loving Sedge');
insert into ingredients (id, name) values (83, 'White Mountain Alumroot');
insert into ingredients (id, name) values (84, 'Needlegrass');
insert into ingredients (id, name) values (85, 'Needlegrass');
insert into ingredients (id, name) values (86, 'Smallhead Cat''s Ear');
insert into ingredients (id, name) values (87, 'Obispo Suncup');
insert into ingredients (id, name) values (88, 'Ditrichum Moss');
insert into ingredients (id, name) values (89, 'Carolina Indigo');
insert into ingredients (id, name) values (90, 'Timber Milkvetch');
insert into ingredients (id, name) values (91, 'Oahu Clermontia');
insert into ingredients (id, name) values (92, 'Ground Orchid');
insert into ingredients (id, name) values (93, 'Pyrenocollema Lichen');
insert into ingredients (id, name) values (94, 'Dandelion');
insert into ingredients (id, name) values (95, 'Clark Mountain Buckwheat');
insert into ingredients (id, name) values (96, 'Arctic Rush');
insert into ingredients (id, name) values (97, 'Veiny Geranium');
insert into ingredients (id, name) values (98, 'Western Blue Virginsbower');
insert into ingredients (id, name) values (99, 'Spreading Pygmyleaf');
insert into ingredients (id, name) values (100, 'Minthorn''s Milkvetch');